# Generated by Django 5.2 on 2025-05-04 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0003_remove_quiz_unique_link_quiz_total_marks_quizlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizlink',
            name='quiz_questions',
        ),
    ]
