# Generated by Django 5.2 on 2025-06-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0004_remove_quizlink_quiz_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='ai_review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='ai_review_generated',
            field=models.BooleanField(default=False),
        ),
    ]
