# Generated by Django 5.2 on 2025-06-15 21:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0005_quizresult_ai_review_quizresult_ai_review_generated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizlink',
            name='completed_by',
            field=models.ManyToManyField(blank=True, related_name='completed_quizzes', to=settings.AUTH_USER_MODEL),
        ),
    ]
